#*******************************************************************************
#* makefile.mk
#*------------------------------------------------------------------------------
#* Makefile used to generate the Application binaries (GNU ARM format).
#* This file was automatically generated by IngeDev. Please, do not edit!
#*******************************************************************************

#-------------------------------------------------------------------------------
# General constants
#-------------------------------------------------------------------------------
EMPTY :=
SPACE := $(EMPTY) $(EMPTY)

#-------------------------------------------------------------------------------
# Project and file names
#-------------------------------------------------------------------------------
# Project name
PROJECT_NAME    := Opus
# Compiler version
COMPILER_VERSION	:= GNU ARM 4.3.4
# Configuration name
CFG_NAME        := GNU_ARM_DEBUG
# Target file name (without extension)
TRG_FILE_NAME   := OPUS
# Startup object file name
STARTUP_OBJ_NAME:= cstartup.o
CGUARD_OBJ_NAME:= __ing_cguard.o
GETRAND_OBJ_NAME:= __ing_getRand_dateXORSerial.o
# Mapping file name
MAPPING_DEF_NAME:= mapping.def


#-------------------------------------------------------------------------------
# Directories
#-------------------------------------------------------------------------------
# Binaries directory
BIN_DIR         := Bin
# Object directory
OBJ_DIR         := Obj
# Build files directory
BUILD_FILES_DIR := BuildFiles

#-------------------------------------------------------------------------------
# Input files path for the current configuration
#-------------------------------------------------------------------------------
# Build files path
BUILD_FILES_PATH:= $(BUILD_FILES_DIR)/$(CFG_NAME)

#-------------------------------------------------------------------------------
# Output files path for the current configuration
#-------------------------------------------------------------------------------
# Object files path
OBJ_PATH        := $(OBJ_DIR)/$(CFG_NAME)
# Binary files path
BIN_PATH        := $(BIN_DIR)/$(CFG_NAME)

#-------------------------------------------------------------------------------
# Compiler, linker, assembler, ...
#-------------------------------------------------------------------------------
# Gnu Compiler executable
CC              := arm-elf-gcc.exe
# Gnu Assembler executable
AS              := arm-elf-as.exe
# Gnu Linker executable
LD              := arm-elf-ld.exe
# Gnu binary file transforming executable
OBJ_COPY        := arm-elf-objcopy.exe
# Gnu binary sections size executable
SIZE            := arm-elf-size.exe
# Gnu binary Obj Dump executable
OBJ_DUMP        := arm-elf-objdump.exe

#-------------------------------------------------------------------------------
# Gnu Win32 tools
#-------------------------------------------------------------------------------
# Remove tool
RM              := rm.exe -fr
# Make directory tool
MKDIR           := mkdir.exe -p
# Copy tool
CP              := cp.exe
# Printf tool
PRINTF          := printf.exe

#-------------------------------------------------------------------------------
# Includes path used in compilation process
#-------------------------------------------------------------------------------
INCLUDES_PATH   := \
-I"Inc" \
-I"C:/Program Files/TeliumSDK/SDK 9.8.0/SDK/inc" \


#-------------------------------------------------------------------------------
# Libraries to be included during link operation
#-------------------------------------------------------------------------------
LIBS            := \
C:/Program\ Files/TeliumSDK/SDK\ 9.8.0/SDK/lib_gnu_434/eft30.lib \
C:/Program\ Files/TeliumSDK/SDK\ 9.8.0/SDK/lib_gnu_434/trap.lib \
C:/Program\ Files/TeliumSDK/SDK\ 9.8.0/SDK/lib_gnu_434/IAPP.lib \
C:/Program\ Files/TeliumSDK/SDK\ 9.8.0/SDK/lib_gnu_434/AVL.lib \
C:/Program\ Files/TeliumSDK/SDK\ 9.8.0/SDK/lib_gnu_434/LinkLayerExeInterface.lib \
C:/Program\ Files/TeliumSDK/SDK\ 9.8.0/SDK/lib_gnu_434/SEC.lib \
C:/Program\ Files/TeliumSDK/SDK\ 9.8.0/SDK/lib_gnu_434/E2EE_DLL.lib \
C:/Program\ Files/TeliumSDK/SDK\ 9.8.0/SDK/lib_gnu_434/Digest.lib \
C:/Program\ Files/TeliumSDK/SDK\ 9.8.0/SDK/lib_gnu_434/SEC_extend.lib \
C:/Program\ Files/TeliumSDK/SDK\ 9.8.0/SDK/lib_gnu_434/dll_wifi.lib \
C:/Program\ Files/TeliumSDK/SDK\ 9.8.0/SDK/lib_gnu_434/FTP_.lib \
C:/Program\ Files/TeliumSDK/SDK\ 9.8.0/SDK/lib_gnu_434/SSL_.lib \
C:/Program\ Files/TeliumSDK/SDK\ 9.8.0/SDK/lib_gnu_434/IP_.lib \
C:/Program\ Files/TeliumSDK/SDK\ 9.8.0/SDK/lib_gnu_434/SNMP_.lib \
C:/Program\ Files/TeliumSDK/SDK\ 9.8.0/SDK/lib_gnu_434/IMG_.lib \
C:/Program\ Files/TeliumSDK/SDK\ 9.8.0/SDK/lib_gnu_434/TPass.lib \
C:/Program\ Files/TeliumSDK/SDK\ 9.8.0/SDK/lib_gnu_434/Mifare.lib \
C:/Program\ Files/TeliumSDK/SDK\ 9.8.0/SDK/lib_gnu_434/GTL.lib \
C:/Program\ Files/TeliumSDK/SDK\ 9.8.0/SDK/lib_gnu_434/libcpatch.o \
C:/Program\ Files/TeliumSDK/SDK\ 9.8.0/SDK/lib_gnu_434/NDEF.lib \

#-------------------------------------------------------------------------------
# System libraries to be included during link operation
#-------------------------------------------------------------------------------
SYSTEM_LIBS     := \
-L C:/Program\ Files/Ingenico/IngeDev_7/plugins/com.ingenico.ingedev.telium.bin.win32.gnuarm.v434_7.16.0.6/os/win32/GNUARM/4.3.4/arm-elf/lib/thumb/soft/interwork -lsupc++ \
-L C:/Program\ Files/Ingenico/IngeDev_7/plugins/com.ingenico.ingedev.telium.bin.win32.gnuarm.v434_7.16.0.6/os/win32/GNUARM/4.3.4/arm-elf/lib/thumb/soft/interwork -lc \
-L C:/Program\ Files/Ingenico/IngeDev_7/plugins/com.ingenico.ingedev.telium.bin.win32.gnuarm.v434_7.16.0.6/os/win32/GNUARM/4.3.4/lib/gcc/arm-elf/4.3.4/thumb/soft/interwork -lgcc 

#-------------------------------------------------------------------------------
# Compilation and link input files
#-------------------------------------------------------------------------------
# Mapping file location (used during link process)
MAP_DEF_LOCATION:= $(BUILD_FILES_PATH)/$(MAPPING_DEF_NAME)

#-------------------------------------------------------------------------------
# Result output files
#-------------------------------------------------------------------------------
# Binary file
BINARY_FILE     := $(BIN_PATH)/$(TRG_FILE_NAME).BIN

#-------------------------------------------------------------------------------
# Result Listing files
#-------------------------------------------------------------------------------
# Binary file
LST_FILE     := $(OBJ_PATH)/$(TRG_FILE_NAME).lst

#-------------------------------------------------------------------------------
# Intermediate files
#-------------------------------------------------------------------------------
# Result map file location
INTER_MAP_FILE  := $(OBJ_PATH)/$(TRG_FILE_NAME).map
# AXF file location
INTER_AXF_FILE  := $(OBJ_PATH)/$(TRG_FILE_NAME).axf
# ELF file location
INTER_ELF_FILE  := $(OBJ_PATH)/$(TRG_FILE_NAME).elf

#-------------------------------------------------------------------------------
# Default compiler, linker, assembler options
#-------------------------------------------------------------------------------
# Default compiler options
CC_DEF_OPTS     := -g -c -Wall -Wcast-align -mthumb-interwork -mlittle-endian -msoft-float -pipe -mcpu=arm920t -fomit-frame-pointer -fshort-enums -mstructure-size-boundary=8 -fno-builtin-fork
# Default assembler options
AS_DEF_OPTS     := --gdwarf2 -mthumb-interwork -EL -mfpu=softfpa -march=armv4t -mcpu=arm9tdmi
# Default linker options
LD_DEF_OPTS     :=  -Map=$(INTER_MAP_FILE)
# Default linker options
OD_DEF_OPTS     := --disassemble --source --syms

#-------------------------------------------------------------------------------
# Specific compiler, linker, assembler options
#-------------------------------------------------------------------------------
# Specific compiler options
CC_SPEC_OPTS    := -mthumb -fno-exceptions -Os -Wuninitialized -fstack-protector-all  -D_ING_GNU_ARM_DEBUG
CC_SPEC_OPTS    +=  -D_EXPORT_ -D_EFT30_ -D__TELIUM2__
CC_SPEC_OPTS    +=  $(INCLUDES_PATH)
# Specific assembler options
AS_SPEC_OPTS    := -mthumb  --defsym _ING_GNU_ARM_DEBUG=1
AS_SPEC_OPTS    +=  --defsym _EXPORT_=1 --defsym _EFT30_=1 --defsym __TELIUM2__=1
AS_SPEC_OPTS    +=  $(INCLUDES_PATH)
# Specific linker options
LD_SPEC_OPTS    := 

#-------------------------------------------------------------------------------
# Compiler, linker, assembler options
# default + specific options
#-------------------------------------------------------------------------------
# Compiler options
CC_OPTS         := $(CC_DEF_OPTS) $(CC_SPEC_OPTS)
# Assembler options
AS_OPTS         := $(AS_DEF_OPTS) $(AS_SPEC_OPTS)
# Linker options
LD_OPTS         := $(LD_DEF_OPTS) $(LD_SPEC_OPTS)
#ObjDump options
OD_OPTS         := $(OD_DEF_OPTS) 

#-------------------------------------------------------------------------------
# SRC_OBJS is the list of the project object files
#-------------------------------------------------------------------------------
SRC_OBJS        := \
$(OBJ_PATH)/Backlight.o \
$(OBJ_PATH)/Boleto.o \
$(OBJ_PATH)/Conn.o \
$(OBJ_PATH)/Dialogs.o \
$(OBJ_PATH)/Entry.o \
$(OBJ_PATH)/File.o \
$(OBJ_PATH)/FTP.o \
$(OBJ_PATH)/GPRS.o \
$(OBJ_PATH)/HTTP.o \
$(OBJ_PATH)/Inicio.o \
$(OBJ_PATH)/Main.o \
$(OBJ_PATH)/Menus.o \
$(OBJ_PATH)/NTP.o \
$(OBJ_PATH)/Sistema.o \
$(OBJ_PATH)/Recarga.o \

#-------------------------------------------------------------------------------
# Dependencies
#-------------------------------------------------------------------------------
DEPENDENCIES    := \
$(BUILD_FILES_PATH)/makefile.mk

#===============================================================================
# Rule to make the project
#===============================================================================
#-------------------------------------------------------------------------------
# Rule for the binary files generation
#-------------------------------------------------------------------------------
$(BINARY_FILE): $(INTER_ELF_FILE) \

	$(OBJ_COPY) -O binary $(INTER_AXF_FILE) $@
	@$(PRINTF) "'$@' binary file generated.\n"

#===============================================================================
# Rule for the link process
#===============================================================================
#-------------------------------------------------------------------------------
# Rule for the axf file generation
#-------------------------------------------------------------------------------
$(INTER_AXF_FILE): $(MAP_DEF_LOCATION) $(SRC_OBJS) $(LIBS)
	@$(PRINTF) "'$@' link in progress...\n"
	@$(CP) "C:\Program Files\Ingenico\IngeDev_7\plugins\com.ingenico.ingedev.telium.core_7.18.1.6\defaultSystemFiles\Obj\gnu_arm4\$(STARTUP_OBJ_NAME)" "$(OBJ_PATH)"
	@$(CP) "C:\Program Files\Ingenico\IngeDev_7\plugins\com.ingenico.ingedev.telium.core_7.18.1.6\defaultSystemFiles\Obj\gnu_arm4\$(CGUARD_OBJ_NAME)" "$(OBJ_PATH)"
	@$(CP) "C:\Program Files\Ingenico\IngeDev_7\plugins\com.ingenico.ingedev.telium.core_7.18.1.6\defaultSystemFiles\Obj\gnu_arm4\$(GETRAND_OBJ_NAME)" "$(OBJ_PATH)"	
	$(LD) $(LD_OPTS) -T $< -o $@ $(SRC_OBJS) $(OBJ_PATH)/$(STARTUP_OBJ_NAME) $(OBJ_PATH)/$(CGUARD_OBJ_NAME) $(OBJ_PATH)/$(GETRAND_OBJ_NAME) -\( $(LIBS) -\) $(SYSTEM_LIBS)

#-------------------------------------------------------------------------------
# Rule for the elf file generation
#-------------------------------------------------------------------------------
$(INTER_ELF_FILE): $(INTER_AXF_FILE)
	$(SIZE) -A $< > $@

#===============================================================================
# Rule for the .lst Generation
#===============================================================================
$(LST_FILE): $(INTER_AXF_FILE)
	$(OBJ_DUMP) $(OD_OPTS) $<  > $@
	@$(PRINTF) "'$@' lst file generated.\n"

#===============================================================================
# Rule for the compilation process
#===============================================================================
ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Backlight.d
endif
$(OBJ_PATH)/Backlight.o: Src/Backlight.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'Src/Backlight.c' compilation in progress...\n"
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Backlight.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Boleto.d
endif
$(OBJ_PATH)/Boleto.o: Src/Boleto.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'Src/Boleto.c' compilation in progress...\n"
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Boleto.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Conn.d
endif
$(OBJ_PATH)/Conn.o: Src/Conn.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'Src/Conn.c' compilation in progress...\n"
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Conn.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Dialogs.d
endif
$(OBJ_PATH)/Dialogs.o: Src/Dialogs.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'Src/Dialogs.c' compilation in progress...\n"
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Dialogs.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Entry.d
endif
$(OBJ_PATH)/Entry.o: Src/Entry.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'Src/Entry.c' compilation in progress...\n"
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Entry.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/File.d
endif
$(OBJ_PATH)/File.o: Src/File.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'Src/File.c' compilation in progress...\n"
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/File.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/FTP.d
endif
$(OBJ_PATH)/FTP.o: Src/FTP.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'Src/FTP.c' compilation in progress...\n"
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/FTP.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/GPRS.d
endif
$(OBJ_PATH)/GPRS.o: Src/GPRS.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'Src/GPRS.c' compilation in progress...\n"
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/GPRS.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/HTTP.d
endif
$(OBJ_PATH)/HTTP.o: Src/HTTP.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'Src/HTTP.c' compilation in progress...\n"
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/HTTP.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Inicio.d
endif
$(OBJ_PATH)/Inicio.o: Src/Inicio.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'Src/Inicio.c' compilation in progress...\n"
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Inicio.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Main.d
endif
$(OBJ_PATH)/Main.o: Src/Main.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'Src/Main.c' compilation in progress...\n"
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Main.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Menus.d
endif
$(OBJ_PATH)/Menus.o: Src/Menus.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'Src/Menus.c' compilation in progress...\n"
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Menus.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/NTP.d
endif
$(OBJ_PATH)/NTP.o: Src/NTP.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'Src/NTP.c' compilation in progress...\n"
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/NTP.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Sistema.d
endif
$(OBJ_PATH)/Sistema.o: Src/Sistema.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'Src/Sistema.c' compilation in progress...\n"
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Sistema.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Recarga.d
endif
$(OBJ_PATH)/Recarga.o: Src/Recarga.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'Src/Recarga.c' compilation in progress...\n"
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Recarga.o)
	@$(PRINTF) "done!\n"
endif

#===============================================================================
# Rule for project name and configuration name display
#===============================================================================
.PHONY: displayInfo
displayInfo:
	@$(PRINTF) "                                     *-*-*\n"
	@$(PRINTF) "--- Project '$(PROJECT_NAME)', Configuration '$(CFG_NAME)', Compiler '$(COMPILER_VERSION)' ---\n"

#===============================================================================
# Rule for build target progress info display
#===============================================================================
.PHONY: displayBuildInProgress
displayBuildInProgress:
	@$(PRINTF) "Build in progress...\n"

#===============================================================================
# Rule for output directories creation
#===============================================================================
.PHONY: createOutputDirs
createOutputDirs:
	@$(MKDIR) "$(OBJ_PATH)"
	@$(MKDIR) "$(BIN_PATH)"

#===============================================================================
# Make build rule
#===============================================================================
.PHONY: build
build: displayInfo displayBuildInProgress createOutputDirs $(BINARY_FILE)
	@$(PRINTF) "done!\n"

#===============================================================================
# Make clean rule
#===============================================================================
.PHONY: clean
clean: displayInfo
	@$(PRINTF) "deleting intermediate files...\n"
	@$(RM) "$(BINARY_FILE)"
ifneq "$(wildcard $(OBJ_PATH)/*.*)" ""
	@$(RM) "$(OBJ_PATH)/*.*"
endif
	@$(PRINTF) "done!\n"
